// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdfXkcAShATRuXML3dHOpXs8h0gbqDnD0',
    appId: '1:1092810052897:web:0cfdc1e8bbd2bfdcc41a60',
    messagingSenderId: '1092810052897',
    projectId: 'vandadcourse',
    authDomain: 'vandadcourse.firebaseapp.com',
    storageBucket: 'vandadcourse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbraQnCJlnxvuTm0v3j_1XY4uAi1ZPMeo',
    appId: '1:1092810052897:android:33edfc39624cb724c41a60',
    messagingSenderId: '1092810052897',
    projectId: 'vandadcourse',
    storageBucket: 'vandadcourse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMyrHletfY6qgPLi037FoK28-AtVyP-co',
    appId: '1:1092810052897:ios:bd7df3ded106c8fac41a60',
    messagingSenderId: '1092810052897',
    projectId: 'vandadcourse',
    storageBucket: 'vandadcourse.appspot.com',
    iosClientId: '1092810052897-e8sct00d467ukoo04ch1b5kqr4ithikq.apps.googleusercontent.com',
    iosBundleId: 'com.misterdiallo.vandadcourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMyrHletfY6qgPLi037FoK28-AtVyP-co',
    appId: '1:1092810052897:ios:bd7df3ded106c8fac41a60',
    messagingSenderId: '1092810052897',
    projectId: 'vandadcourse',
    storageBucket: 'vandadcourse.appspot.com',
    iosClientId: '1092810052897-e8sct00d467ukoo04ch1b5kqr4ithikq.apps.googleusercontent.com',
    iosBundleId: 'com.misterdiallo.vandadcourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdfXkcAShATRuXML3dHOpXs8h0gbqDnD0',
    appId: '1:1092810052897:web:cebb3a82cd4fda13c41a60',
    messagingSenderId: '1092810052897',
    projectId: 'vandadcourse',
    authDomain: 'vandadcourse.firebaseapp.com',
    storageBucket: 'vandadcourse.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBdfXkcAShATRuXML3dHOpXs8h0gbqDnD0',
    appId: '1:1092810052897:web:a8340dec5537964fc41a60',
    messagingSenderId: '1092810052897',
    projectId: 'vandadcourse',
    authDomain: 'vandadcourse.firebaseapp.com',
    storageBucket: 'vandadcourse.appspot.com',
  );
}
